//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodDelivery.Web.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FoodListComponentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FoodListComponentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodDelivery.Web.App.Resources.FoodListComponentResources", typeof(FoodListComponentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddRestaurant {
            get {
                return ResourceManager.GetString("AddRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allergens.
        /// </summary>
        public static string Allergens_FilterLabel {
            get {
                return ResourceManager.GetString("Allergens_FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foods.
        /// </summary>
        public static string Foods_Title {
            get {
                return ResourceManager.GetString("Foods_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This restaurant has no foods..
        /// </summary>
        public static string NoFoods {
            get {
                return ResourceManager.GetString("NoFoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by.
        /// </summary>
        public static string OrderBy_Label {
            get {
                return ResourceManager.GetString("OrderBy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string OrderBy_Option_Default {
            get {
                return ResourceManager.GetString("OrderBy_Option_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (ascending).
        /// </summary>
        public static string OrderBy_Option_OrderByNameAsc {
            get {
                return ResourceManager.GetString("OrderBy_Option_OrderByNameAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (descending).
        /// </summary>
        public static string OrderBy_Option_OrderByNameDesc {
            get {
                return ResourceManager.GetString("OrderBy_Option_OrderByNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (ascending).
        /// </summary>
        public static string OrderBy_Option_OrderByPriceAsc {
            get {
                return ResourceManager.GetString("OrderBy_Option_OrderByPriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price (descending).
        /// </summary>
        public static string OrderBy_Option_OrderByPriceDesc {
            get {
                return ResourceManager.GetString("OrderBy_Option_OrderByPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string Restaurants_Breadcrumb {
            get {
                return ResourceManager.GetString("Restaurants_Breadcrumb", resourceCulture);
            }
        }
    }
}
